### ISSUE TITLE
Check out using r rig options to make a simpler container

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/codespaces4r#1]
https://github.com/rocker-org/devcontainer-features/blob/main/src/r-rig/README.md

This seems to have options to make R usable in VS code, like installing Radian, and the necessary R pkgs. This may be a cleaner way to a usable R dev environment.

**Comment by eitsupi** [comment]
> This seems to have options to make R usable in VS code, like installing Radian, and the necessary R pkgs. This may be a cleaner way to a usable R dev environment.

You are right. This was created to replace the scripts in [the Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/f03374c122d7c5a8d04d7624b7d2dc31cdda7a86/containers/r/.devcontainer/Dockerfile) as a Dev Container Feature.

Similarly, the `common-debian.sh` script is replaced by the common-utils Feature.
https://github.com/devcontainers/features/tree/main/src/common-utils

This means the following.
https://github.com/rocker-org/devcontainer-images/tree/main/src/r-ver

See also #3
