### ISSUE TITLE
Consider using the new Dev Container Template-base files

### ISSUE THREAD

**Issue by eitsupi** [nmfs-fish-tools/codespaces4r#3]
Hello.
It looks like you are using old https://github.com/microsoft/vscode-dev-containers/tree/main/containers/r based files for this project.
Currently https://github.com/microsoft/vscode-dev-containers/tree/main/containers/r is deprecated and the new https://github.com/rocker-org/devcontainer-templates/tree/main/src/r-ver can be used.
I am a contributor to both them and have done quite a bit of work for the new Template recently.
Please consider using the new Template.

Thanks.

**Comment by k-doering-NOAA** [comment]
Thank you @eitsupi! We found the new options much simpler :)
